tap "buo/cask-upgrade"
tap "cormacrelf/tap"
tap "daipeihust/tap"
tap "dimentium/autoraise"
tap "homebrew/bundle"
tap "homebrew/services"
tap "homebrew/test-bot"
tap "jesseduffield/lazydocker"
tap "jesseduffield/lazygit"
tap "joelekstrom/repo"
tap "owo-network/brew"
tap "yt-dlp/taps"
# TIFF library and utilities
brew "libtiff"
# High dynamic-range image file format
brew "openexr"
# Library for command-line editing
brew "readline"
# Command-line interface for SQLite
brew "sqlite"
# Download with resuming and segmented downloading
brew "aria2"
# Shell extension to jump to frequently used directories
brew "autojump"
# Bourne-Again SHell, a UNIX command interpreter
brew "bash"
# Clone of cat(1) with syntax highlighting and Git integration
brew "bat"
# Platform built on V8 to build network applications
brew "node"
# Secure and free password manager for all of your devices
brew "bitwarden-cli"
# Connect and disconnect Bluetooth devices
brew "bluetoothconnector"
# Get/set bluetooth power and discoverable state
brew "blueutil"
# Yet another cross-platform graphical process/system monitor
brew "bottom"
# Software library to render fonts
brew "freetype"
# Core application library for C
brew "glib"
# X.Org: Interface to the X Window System protocol
brew "libxcb"
# X.Org: Core X11 protocol client library
brew "libx11"
# Versatile and fast Unicode/ASCII/ANSI graphics renderer
brew "chafa"
# Manage your dotfiles across multiple diverse machines, securely
brew "chezmoi"
# Human-friendly and fast alternative to cut and (sometimes) awk
brew "choose-rust"
# Tool for emulating mouse and keyboard events
brew "cliclick"
# Get a file from an HTTP, HTTPS or FTP server
brew "curl"
# Open source suite of directory software
brew "openldap"
# General-purpose scripting language
brew "php"
# Dependency Manager for PHP
brew "composer"
# GNU File, Shell, and Text utilities
brew "coreutils"
# Configurable talking characters in ASCII art
brew "cowsay"
# Power of curl, ease of use of httpie
brew "curlie"
# Command-line tool for getting & setting the default browser
brew "defaultbrowser"
# Secure communications between a client and a DNS resolver
brew "dnscrypt-proxy"
# Simple, fast and user-friendly alternative to find
brew "fd"
# Asynchronous event library
brew "libevent"
# Low-level cryptographic library
brew "nettle"
# Validating, recursive, caching DNS resolver
brew "unbound"
# Multi-format archive and compression library
brew "libarchive"
# Fastest and safest AV1 video encoder
brew "rav1e"
# Play, record, convert, and stream audio and video
brew "ffmpeg"
# Banner-like program prints strings as ASCII art
brew "figlet"
# Collection of GNU find, xargs, and locate
brew "findutils"
# Command-line fuzzy finder written in Go
brew "fzf"
# GitHub command-line tool
brew "gh"
# Distributed revision control system
brew "git"
# Syntax-highlighting pager for git and diff output
brew "git-delta"
# Extensions to follow Vincent Driessen's branching model
brew "git-flow"
# Git extension for versioning large files
brew "git-lfs"
# C library for encoding, decoding, and manipulating JSON
brew "jansson"
# YAML Parser
brew "libyaml"
# Source code tag system
brew "global"
# GNU Pretty Good Privacy (PGP) package
brew "gnupg"
# Open source programming language to build simple/reliable/efficient software
brew "go"
# GNU grep, egrep and fgrep
brew "grep"
# Powerful, lightweight programming language
brew "lua"
# Convert source code to formatted text with syntax highlighting
brew "highlight"
# Configurable static site generator
brew "hugo"
# Tools and libraries to manipulate images in many formats
brew "imagemagick"
# Update of iperf: measures TCP, UDP, and SCTP bandwidth
brew "iperf3"
# Image manipulation library
brew "jpeg"
# Lightweight and flexible command-line JSON processor
brew "jq"
# Pager program similar to more
brew "less"
# Configuration file processing library
brew "libconfig"
# X.Org: X Toolkit Intrinsics library
brew "libxt"
# Package manager for the Lua programming language
brew "luarocks"
# Language Server Protocol for Markdown
brew "marksman"
# Mac App Store command-line interface
brew "mas"
# Ambitious Vim-fork focused on extensibility and agility
brew "neovim"
# Port scanning utility for large networks
brew "nmap"
# Retrieves currently playing media, and simulates media actions
brew "nowplaying-cli"
# Ncurses based sudoku game
brew "nudoku"
# Tools for one-time password authentication systems
brew "oath-toolkit"
# Swiss-army knife of markup format conversion
brew "pandoc"
# Pandoc filter for numbering and cross-referencing
brew "pandoc-crossref"
# Python dependency management tool
brew "pipenv"
# Paste PNG into files
brew "pngpaste"
# Theme for zsh
brew "powerlevel10k"
# Protocol buffers (Google's data interchange format)
brew "protobuf"
# Search tool like grep and The Silver Searcher
brew "ripgrep"
# Powerful, clean, object-oriented scripting language
brew "ruby"
# Intuitive find & replace CLI
brew "sd"
# CLI and dbus interface for WhisperSystems/libsignal-service-java
brew "signal-cli"
# Prints a steam locomotive if you type sl instead of ls
brew "sl"
# SOcket CAT: netcat on steroids
brew "socat"
# Change macOS audio source from the command-line
brew "switchaudio-osx"
# Manipulate and query tags on macOS files
brew "tag"
# Send macOS User Notifications from the command-line
brew "terminal-notifier"
# Code-search similar to ack
brew "the_silver_searcher"
# Official tldr client written in Rust
brew "tlrc"
# Terminal multiplexer
brew "tmux"
# CLI tool that moves files or folder to the trash
brew "trash"
# Display directories as trees (with optional color/HTML output)
brew "tree"
# Check your $HOME for unwanted files and directories
brew "xdg-ninja"
# Hackable, minimal, fast TUI file explorer
brew "xplr"
# JavaScript package manager
brew "yarn"
# Feature-rich command-line audio/video downloader
brew "yt-dlp"
# Real-time type-ahead completion for Zsh
brew "zsh-autocomplete"
# Fish-like fast/unobtrusive autosuggestions for zsh
brew "zsh-autosuggestions"
# Watcher for macOS 10.14+ light/dark mode changes
brew "cormacrelf/tap/dark-notify"
# Switch your input method through terminal
brew "daipeihust/tap/im-select"
# Focus-follows-mouse for MacOS
brew "dimentium/autoraise/autoraise", args: ["with-dexperimental_focus_first"]
# A simple terminal UI for docker, written in Go
brew "jesseduffield/lazydocker/lazydocker"
# A simple terminal UI for git commands, written in Go
brew "jesseduffield/lazygit/lazygit"
# An ncurses-based minesweeper game
brew "joelekstrom/repo/terminal-mines"
# DeepLX is a permanently free DeepL API client written in Golang.
brew "owo-network/brew/deeplx"
# GPU-accelerated terminal emulator
cask "alacritty"
# Application launcher and productivity software
cask "alfred"
# Enable Windows-like alt-tab
cask "alt-tab"
# Inspect application bundles
cask "apparency"
# Application uninstaller
cask "appcleaner"
# Chromium based browser
cask "arc"
# Menu bar icon organiser
cask "bartender"
# App for managing battery charging. (Also installs a CLI on first use.)
cask "battery"
# Utility to create and modify archives
cask "betterzip"
# OpenAI's official ChatGPT desktop app
cask "chatgpt"
# Chinese-German dictionary
cask "dehelper"
# App to build and share containerised applications and microservices
cask "docker"
# Calendar software
cask "fantastical"
# Collaborative team software
cask "figma"
cask "font-lxgw-bright"
# Tool that helps teams design every part of the product experience
cask "framer"
# Git interface focused on visual interaction
cask "gitup"
# Web browser
cask "google-chrome"
# Desktop automation application
cask "hammerspoon"
# Free and open-source media player
cask "iina"
# Multi-touch gestures editor
cask "jitouch"
# Keyboard customiser
cask "karabiner-elements"
# Password manager app
cask "keepassxc"
# File archiver
cask "keka"
# Open-source keystroke visualiser
cask "keycastr"
# Open-source firewall to block unknown outgoing connections
cask "lulu"
# Adaptive brightness for external displays
cask "lunar"
# Extensible two-pane file manager
cask "marta"
# Minimal installer for conda
cask "miniconda"
# Add more gestures for Trackpad and Magic Mouse
cask "multitouch"
# Screensaver displaying artwork based on Spotify or Last.fm profile data
cask "musaicfm"
# Desktop sync client for Nextcloud software products
cask "nextcloud"
# Knowledge base that works on top of a local folder of plain text Markdown files
cask "obsidian"
# Finds large, unwanted files and deletes them
cask "omnidisksweeper"
# Read, annotate, edit, convert, create, OCR, fill forms and sign PDFs
cask "pdf-reader-pro"
# VPN client focusing on security
cask "protonvpn"
# Quick Look plugin for mobile apps and provisioning profiles
cask "provisionql"
# Quick Look generator for Markdown files
cask "qlmarkdown"
# Quick Look plugin for plaintext files without an extension
cask "qlstephen"
# Thumbnails, static previews, cover art and metadata for video files
cask "qlvideo"
# Quick Look plugin for CSV files
cask "quicklook-csv"
# Quick Look plugin for JSON files
cask "quicklook-json"
# Environment for statistical computing and graphics
cask "r"
# Create, edit, browse SQLite databases
cask "sqlitestudio"
# Quicklook extension for source files
cask "syntax-highlight"
# Utility for producing audio feedback when typing
cask "tickeys"
# Run commands and display their output on the desktop
cask "ubersicht"
# Open-source code editor
cask "visual-studio-code"
# Collect, organise, cite, and share research sources
cask "zotero"
mas "AdBlock", id: 1402042596
mas "Amphetamine", id: 937984704
mas "Bitwarden", id: 1352778147
mas "Bob", id: 1630034110
mas "Dark Reader for Safari", id: 1438243180
mas "Encrypto", id: 935235287
mas "Keynote 讲演", id: 409183694
mas "Keyword Search", id: 1558453954
mas "Numbers 表格", id: 409203825
mas "Pages 文稿", id: 409201541
mas "Pixelmator Pro", id: 1289583905
mas "Remote Mouse", id: 403195710
mas "Spark", id: 1176895641
mas "Tampermonkey", id: 1482490089
mas "Tencent Lemon Lite", id: 1449962996
mas "uBlacklist for Safari", id: 1547912640
mas "Vimari", id: 1480933944
mas "WireGuard", id: 1451685025
vscode "animaapp.vscode-anima"
vscode "baurine.vscode-pangu"
vscode "davidanson.vscode-markdownlint"
vscode "dbaeumer.vscode-eslint"
vscode "donjayamanne.githistory"
vscode "eamodio.gitlens"
vscode "ecmel.vscode-html-css"
vscode "eeyore.yapf"
vscode "esbenp.prettier-vscode"
vscode "felipecaputo.git-project-manager"
vscode "figma.figma-vscode-extension"
vscode "formulahendry.auto-close-tag"
vscode "formulahendry.auto-rename-tag"
vscode "formulahendry.code-runner"
vscode "gera2ld.markmap-vscode"
vscode "github.codespaces"
vscode "github.copilot"
vscode "github.copilot-chat"
vscode "github.github-vscode-theme"
vscode "github.remotehub"
vscode "github.vscode-pull-request-github"
vscode "golang.go"
vscode "gruntfuggly.todo-tree"
vscode "ionutvmi.path-autocomplete"
vscode "kortina.vscode-markdown-notes"
vscode "mdickin.markdown-shortcuts"
vscode "mechatroner.rainbow-csv"
vscode "ms-azuretools.vscode-docker"
vscode "ms-python.debugpy"
vscode "ms-python.python"
vscode "ms-python.vscode-pylance"
vscode "ms-toolsai.jupyter"
vscode "ms-toolsai.jupyter-keymap"
vscode "ms-toolsai.jupyter-renderers"
vscode "ms-toolsai.vscode-jupyter-cell-tags"
vscode "ms-toolsai.vscode-jupyter-slideshow"
vscode "ms-vscode-remote.remote-ssh"
vscode "ms-vscode-remote.remote-ssh-edit"
vscode "ms-vscode.remote-explorer"
vscode "ms-vscode.remote-repositories"
vscode "mtxr.sqltools"
vscode "mtxr.sqltools-driver-sqlite"
vscode "notzaki.pandocciter"
vscode "qwtel.sqlite-viewer"
vscode "rdebugger.r-debugger"
vscode "reditorsupport.r"
vscode "rvest.vs-code-prettier-eslint"
vscode "sswg.swift-lang"
vscode "streetsidesoftware.code-spell-checker"
vscode "streetsidesoftware.code-spell-checker-german"
vscode "tomoki1207.pdf"
vscode "vadimcn.vscode-lldb"
vscode "vincaslt.highlight-matching-tag"
vscode "vscodevim.vim"
vscode "vsls-contrib.gistfs"
vscode "yzhang.markdown-all-in-one"
vscode "zainchen.json"
