disableStartupPopups: true
promptToReturnFromSubprocess: false
quitOnTopLevelReturn: true
gui:
  shortTimeFormat: "15:04"
  showBottomLine: false
  nerdFontsVersion: "3"
  showFileIcons: false
  showListFooter: false
  theme:
    activeBorderColor:
      - default
      - bold
    selectedLineBgColor:
      - underline
os:
  # editPreset: "nvim-remote"
  editInTerminal: true
  edit: "$XDG_CONFIG_HOME/lazygit/edit.sh {{filename}}"
  editAtLine: "$XDG_CONFIG_HOME/lazygit/edit.sh {{filename}} +{{line}}"
  copyToClipboardCmd: "echo -n {{text}} | tmux load-buffer -"
git:
  paging:
    colorArg: always
    pager: delta --$(~/.local/bin/background) --paging=never --hyperlinks-file-link-format="lazygit-edit://{path}:{line}"
  truncateCopiedCommitHashesTo: 12
keybinding:
  universal:
    optionMenu: '?'
    optionMenu-alt1: '?'
customCommands:
  - key: 'P'
    context: "remotes"
    command: "git push {{.SelectedRemote.Name}}"
    description: "Push to remote"
  - key: 'p'
    context: "remotes"
    command: "git pull {{.SelectedRemote.Name}}"
    description: "Pull from remote"
  - key: '<c-o>'
    context: "remotes"
    command: |
      url=$(git config --get remote.{{.SelectedRemote.Name}}.url); url=$(echo $url | perl -pe 's/.+(git(hub|lab).com)[:\/]([^\/]+\/[^\/]+?)/https:\/\/\1\/\3/g'); [ -z $url ] || open $url
    description: "Open remote in browser"
  - key: 'f'
    command: "git difftool -y {{.SelectedLocalCommit.Sha}} -- {{.SelectedCommitFile.Name}}"
    context: 'commitFiles'
    description: 'Compare (difftool) with local copy'
