disableStartupPopups: true
promptToReturnFromSubprocess: false
quitOnTopLevelReturn: true
gui:
  shortTimeFormat: "15:04"
  showBottomLine: false
  nerdFontsVersion: "3"
  showFileIcons: false
  showListFooter: false
  theme:
    activeBorderColor:
      - "#b15c00"
      - "bold"
    inactiveBorderColor:
      - "#4094a3"
    searchingActiveBorderColor:
      - "#b15c00"
      - "bold"
    optionsTextColor:
      - "#2e7de9"
    selectedLineBgColor:
      - underline
    cherryPickedCommitFgColor:
      - "#2e7de9"
    cherryPickedCommitBgColor:
      - "#B1E647"
    markedBaseCommitFgColor:
      - "#2e7de9"
    markedBaseCommitBgColor:
      - "#8c6c3e"
    unstagedChangesColor:
      - "#c64343"
    defaultFgColor:
      - "#5A7BC6"
os:
  # editPreset: "nvim-remote"
  editInTerminal: false
  edit: "$XDG_CONFIG_HOME/lazygit/edit.sh {{filename}}"
  editAtLine: "$XDG_CONFIG_HOME/lazygit/edit.sh {{filename}} +{{line}}"
  copyToClipboardCmd: "echo -n {{text}} | tmux load-buffer -"
  readFromClipboardCmd: "tmux show-buffer"
git:
  paging:
    colorArg: always
    pager: delta --$(~/.local/bin/background) --paging=never --hyperlinks-file-link-format="lazygit-edit://{path}:{line}"
  truncateCopiedCommitHashesTo: 12
  overrideGpg: true
keybinding:
  universal:
    optionMenu: '?'
    optionMenu-alt1: '?'
    openRecentRepos: '<c-g>'
customCommands:
  - key: 'P'
    context: "remotes"
    command: "git push {{.SelectedRemote.Name}}"
    description: "Push to remote"
  - key: 'p'
    context: "remotes"
    command: "git pull {{.SelectedRemote.Name}}"
    description: "Pull from remote"
  - key: '<c-o>'
    context: "remotes"
    command: |
      {{range .SelectedRemote.Urls}}
        url=$(echo {{.}} | perl -pe 's/.+(git(hub|lab).com)[:\/]([^\/]+\/[^\/]+?)/https:\/\/\1\/\3/g'); [ -z $url ] || open $url
      {{end}}
    description: "Open remote in browser"
  - key: '<c-y>'
    context: "remotes"
    command: |
      {{range .SelectedRemote.Urls}}
        echo -n {{.}} | tmux load-buffer -
      {{end}}
    description: "Copy remote url"
