disableStartupPopups: true
promptToReturnFromSubprocess: false
quitOnTopLevelReturn: true
gui:
  shortTimeFormat: "15:04"
  showBottomLine: false
  nerdFontsVersion: "3"
  showFileIcons: false
  showListFooter: false
  theme:
    activeBorderColor:
      - default
      - bold
    selectedLineBgColor:
      - underline
os:
  # editPreset: "nvim-remote"
  editInTerminal: true
  edit: "$XDG_CONFIG_HOME/lazygit/edit.sh {{filename}}"
  editAtLine: "$XDG_CONFIG_HOME/lazygit/edit.sh {{filename}} +{{line}}"
  copyToClipboardCmd: "echo -n {{text}} | tmux load-buffer -"
git:
  paging:
    colorArg: always
    pager: "delta --$($HOME/bin/background) --paging=never"
  truncateCopiedCommitHashesTo: 12
keybinding:
  universal:
    optionMenu: '?'
    optionMenu-alt1: '?'
