# https://github.com/sxyazi/yazi/blob/shipped/yazi-config/preset/keymap.toml

[manager]
prepend_keymap = [
  # { on = [ "g", "a" ], run = 'my-fev-command1', desc = "Just for test!" },
  { on = "<A-j>", run = [ 'select', 'arrow 1' ], desc = "Toggle selection" },
  { on = "<A-k>", run = [ 'select --state=false' ], desc = "Toggle selection" },
  { on = "<Enter>", run = 'plugin smart --args=enter --sync', desc = "Open shell / edit file" },
  { on = "<A-Enter>", run = [ 'open --interactive' ], desc = "Open selected files interactively" },
  { on = "?", run = 'help', desc = "Open help" },
  { on = "~", run = 'cd ~', desc = "Go to the home directory" },
  { on = "q", run = 'close', desc = "Close the current tab, or quit if it is last tab" },
  { on = "Q", run = 'quit', desc = "Exit the process" },
  { on = "<C-d>", run = "seek 5", desc = "Seek down 5 units in the preview" },
  { on = "<C-u>", run = "seek -5", desc = "Seek up 5 units in the preview" },
  { on = [ "y", "f" ], run = "yank", desc = "Yank selected files (copy)" },
  { on = [ "y", "p" ], run = "copy path", desc = "Copy the file path" },
  { on = [ "y", "n" ], run = "copy filename", desc = "Copy the filename" },
  { on = "<Esc>", run = 'plugin smart --args=esc --sync', desc = "Unyank, exit visual mode, clear seleted, or canel search" },
  { on = [ "\\", "g" ], run = "plugin my-fzf --args=z", desc = "Jump to a directory using zoxide" },
  { on = [ "\\", "f" ], run = "plugin my-fzf --args=fd", desc = "Jump to a directory or reveal a file using fzf" },
  { on = [ "\\", "s" ], run = "plugin my-fzf --args=fif", desc = "Search files by content using repgrep" },
  { on = [ "\\", "r" ], run = "plugin my-fzf --args=mru", desc = "Search files by content using repgrep" },
  { on = [ "\\", "R" ], run = "plugin my-fzf --args=git", desc = "Search files by content using repgrep" },
]

[tasks]
prepend_keymap = [
  { on = "?", run = 'help', desc = "Open help" },
]

[select]
prepend_keymap = [
  { on = "?", run = 'help', desc = "Open help" },
]

[input]
prepend_keymap = [
  { on = "<esc>", run = 'close', desc = "cancel input" },
  { on = "?", run = 'help', desc = "Open help" },
]

[confirm]
prepend_keymap = [
  { on = "?", run = 'help', desc = "Open help" },
]

[completion]
prepend_keymap = [
  { on = "?", run = 'help', desc = "Open help" },
]

