# https://github.com/sxyazi/yazi/blob/shipped/yazi-config/preset/keymap-default.toml

[manager]
prepend_keymap = [
  { on = "<A-j>", run = [ "toggle", "arrow 1" ], desc = "Toggle selection" },
  { on = "<Tab>", run = [ "toggle", "arrow 1" ], desc = "Toggle selection" },
  { on = "<A-k>", run = "toggle --state=off", desc = "Toggle selection" },
  { on = "<A-a>", run = "toggle_all", desc = "Toggle select all" },
  { on = "i", run = "spot", desc = "Inspect file" },
  { on = "<Enter>", run = "plugin my-cmd 'smart enter'", desc = "Open shell / edit file" },
  { on = "<A-Enter>", run = "open --interactive", desc = "Open selected files interactively" },
  { on = "?", run = "help", desc = "Open help" },
  { on = "!", run = "shell --interactive", desc = "Run a shell command" },
  { on = "~", run = "cd ~", desc = "Go to home directory" },
  { on = "q", run = "close", desc = "Close current tab, or quit if it is last tab" },
  { on = "Q", run = "quit", desc = "Exit" },
  { on = "<C-d>", run = "seek 5", desc = "Seek down 5 units in preview" },
  { on = "<C-u>", run = "seek -5", desc = "Seek up 5 units in preview" },
  { on = [ "g", "d" ], run = "noop" },
  { on = [ "g", "c" ], run = "noop" },
  { on = [ "g", "o" ], run = 'shell -- ya emit reveal "$(realpath "$1")"', desc = "Go to original" },
  { on = [ "g", "p" ], run = 'shell -- ya emit reveal "$(pbpaste)"', desc = "Go to copied path" },
  { on = [ "g", "<Space>" ], run = "cd --interactive", desc = "Go interactively" },
  { on = [ "g", "s" ], run = 'shell --block lazygit', desc = "LazyGit" },
  { on = [ "g", "r" ], run = 'shell -- ya emit cd "$(git rev-parse --show-toplevel)"', desc = "Go to git repo root" },
  { on = [ "g", "<C-d>" ], run = 'shell --block -- git diff "$1" | delta --$(background) --navigate --tabs=2 --line-numbers --side-by-side --paging=always --width=$(stty size < /dev/tty | choose 1)  | less -R', desc = "Git diff" },
  { on = [ "y", "c" ], run = "yank", desc = "Copy selected files" },
  { on = [ "y", "x" ], run = "yank --cut", desc = "Cut selected files" },
  { on = [ "y", "p" ], run = "copy path", desc = "Copy file path" },
  { on = [ "y", "n" ], run = "copy filename", desc = "Copy filename" },
  { on = "<Esc>", run = "plugin my-cmd 'smart esc'", desc = "Unyank, exit visual mode, clear selected, or cancel search" },
  { on = "j", run = "plugin my-cmd 'smart down'", desc = "Move cursor down" },
  { on = "k", run = "plugin my-cmd 'smart up'", desc = "Move cursor up" },
  { on = "<Down>", run = "plugin my-cmd 'smart down'", desc = "Move cursor down" },
  { on = "<Up>", run = "plugin my-cmd 'smart up'", desc = "Move cursor up" },
  { on = "<", run = "back", desc = "Back" },
  { on = ">", run = "forward", desc = "Forward" },
  { on = "J", run = "plugin my-cmd 'smart parent-down'", desc = "Go down in parent dir" },
  { on = "K", run = "plugin my-cmd 'smart parent-up'", desc = "Go up in parent dir" },
  { on = "N", run = "plugin my-cmd 'smart new'", desc = "Go to previous found / Create a file" },
  { on = "<C-t>", run = "plugin my-cmd 'smart tab'", desc = "Create new tab" },
  { on = "<C-v>", run = 'shell -- if [ -n "$TMUX_POPUP" ]; then tmux_edit -cc vsplit "$1"; tmux popup -C; elif [ -n "$NVIM" ]; then nvr -cc quit -cc vsplit "$1"; fi', desc = "Open file in vsplit" },
  { on = "<C-s>", run = 'shell -- if [ -n "$TMUX_POPUP" ]; then tmux_edit -cc split "$1"; tmux popup -C; elif [ -n "$NVIM" ]; then nvr -cc quit -cc split "$1"; fi', desc = "Open file in split" },
  { on = "<C-e>", run = '''shell --block -- nvim "+lua require('mini.files').open('$1')"''', desc = "Open file explorer" },
  { on = "]", run = "plugin my-cmd 'smart next-tab'", desc = "Switch to next tab" },
  { on = [ "<Space>", "u" ], run = "shell --block -- dust -C -w $(stty size < /dev/tty | awk '{print $2}') -n $(stty size < /dev/tty | awk '{print $1 - 2}') . | less -R", desc = "Disk usage" },
  { on = [ "<Space>", "C" ], run = "plugin ouch zip", desc = "Compress" },
  { on = [ "<Space>", "t" ], run = "tasks_show", desc = "Show task manager" },
  { on = [ "<Space>", "s" ], run = "plugin my-fzf selected", desc = "List selected files" },
  { on = [ "<Space>", "m" ], run = "plugin mount", desc = "List mount points" },
  { on = [ "<Space>", "<Enter>" ], run = "plugin my-cmd 'smart alt-enter'", desc = "Open in new window" },
  { on = [ "\\", "g" ], run = "plugin my-fzf z", desc = "Go to a directory" },
  { on = [ "\\", "f" ], run = "plugin my-fzf fd", desc = "Search files" },
  { on = [ "\\", "s" ], run = "plugin my-fzf fif", desc = "Search file contents" },
  { on = [ "\\", "o" ], run = "plugin my-fzf obsearch", desc = "Search Obsidian vault" },
  { on = [ "\\", "r" ], run = "plugin my-fzf git", desc = "Search repos" },
  { on = [ "M", "." ], run = "linemode size_and_mtime", desc = "Linemode: size & mtime" },
  { on = [ "M", "s" ], run = "linemode size",        desc = "Linemode: size" },
  { on = [ "M", "p" ], run = "linemode permissions", desc = "Linemode: permissions" },
  { on = [ "M", "b" ], run = "linemode btime",       desc = "Linemode: btime" },
  { on = [ "M", "m" ], run = "linemode mtime",       desc = "Linemode: mtime" },
  { on = [ "M", "o" ], run = "linemode owner",       desc = "Linemode: owner" },
  { on = [ "M", "n" ], run = "linemode none",        desc = "Linemode: none" },
  { on = [ "m", "s" ], run = "noop" },
  { on = [ "m", "p" ], run = "noop" },
  { on = [ "m", "b" ], run = "noop" },
  { on = [ "m", "m" ], run = "noop" },
  { on = [ "m", "o" ], run = "noop" },
  { on = [ "m", "n" ], run = "noop" },
  { on = [ "S", "m" ], run = [ "sort mtime --reverse=no", "linemode mtime" ], desc = "Sort by modified time" },
  { on = [ "S", "M" ], run = [ "sort mtime --reverse", "linemode mtime" ],    desc = "Sort by modified time (reverse)" },
  { on = [ "S", "c" ], run = [ "sort btime --reverse=no", "linemode btime" ], desc = "Sort by created time" },
  { on = [ "S", "C" ], run = [ "sort btime --reverse", "linemode btime" ],    desc = "Sort by created time (reverse)" },
  { on = [ "S", "e" ], run = "sort extension --reverse=no",                   desc = "Sort by extension" },
  { on = [ "S", "E" ], run = "sort extension --reverse",                      desc = "Sort by extension (reverse)" },
  { on = [ "S", "a" ], run = "sort alphabetical --reverse=no",                desc = "Sort alphabetically" },
  { on = [ "S", "A" ], run = "sort alphabetical --reverse",                   desc = "Sort alphabetically (reverse)" },
  { on = [ "S", "n" ], run = "sort natural --reverse=no",                     desc = "Sort naturally" },
  { on = [ "S", "N" ], run = "sort natural --reverse",                        desc = "Sort naturally (reverse)" },
  { on = [ "S", "s" ], run = [ "sort size --reverse=no", "linemode size" ],   desc = "Sort by size" },
  { on = [ "S", "S" ], run = [ "sort size --reverse", "linemode size" ],      desc = "Sort by size (reverse)" },
  { on = [ "S", "r" ], run = "sort random --reverse=no",                      desc = "Sort randomly" },
  { on = "s", run = "plugin searchjump autocd", desc = "Searchjump" },
  { on = "F", run = "plugin smart-filter", desc = "Smart filter" },
  { on = "a", run = 'shell -- alfred "$1"', desc = "Show file in Alfred" },
  { on = "=", run = 'shell -- altr -w com.nyako520.syspre -t buffer -a - "$@"', desc = "Add file to Alfred buffer" },
  { on = "A", run = 'shell -- altr -w com.nyako520.alfred -t action -a - "$@"', desc = "Action on file in Alfred" },
  { on = ["<A-l>", "c"], run = "plugin my-cmd 'on_selection copy'", desc = "Copy selected files here" },
  { on = ["<A-l>", "C"], run = "plugin my-cmd 'on_selection copy-force'", desc = "Force-copy selected files here" },
  { on = ["<A-l>", "m"], run = "plugin my-cmd 'on_selection move'", desc = "Move selected files here" },
  { on = ["<A-l>", "M"], run = "plugin my-cmd 'on_selection move-force'", desc = "Force-move selected files here" },
  { on = ["<A-l>", "n"], run = "plugin my-cmd 'on_selection move-new-dir'", desc = "Create folder with selected files" },
  { on = ["<A-l>", "N"], run = "plugin my-cmd 'on_selection copy-new-dir'", desc = "Create folder with selected files (copy)" },
  { on = ["<A-l>", "l"], run = "plugin my-cmd 'on_selection symlink'", desc = "Symlink selected files here" },
  { on = ["<A-l>", "L"], run = "plugin my-cmd 'on_selection symlink-force'", desc = "Force-symlink selected files here" },
  { on = ["<A-l>", "h"], run = "plugin my-cmd 'on_selection hardlink'", desc = "Hardlink selected files here" },
  { on = ["<A-l>", "H"], run = "plugin my-cmd 'on_selection hardlink-force'", desc = "Force-hardlink selected files here" },
  { on = ["<A-l>", "d"], run = "plugin my-cmd 'on_selection delete'", desc = "Delete selected files" },
  { on = ["<A-l>", "e"], run = "plugin my-cmd 'on_selection edit'", desc = "Edit selected files" },
  { on = ["<A-l>", "r"], run = "plugin my-cmd 'on_selection rename'", desc = "Rename selected files" },
  { on = ["<A-l>", "<C-d>"], run = 'shell --block -- [ $# -eq 2 ] && delta --$(~/.local/bin/background) --navigate --tabs=2 --line-numbers --side-by-side --paging=always --width=$(stty size < /dev/tty | choose 1) "$@" | less -R || true', desc = "Diff selected files" },
  { on = ["z", "p"], run = "plugin toggle-pane max-preview", desc = "Zoom preview" },
  { on = ["z", "z"], run = "plugin toggle-pane ratio-1,4,0", desc = "Hide preview" },
  { on = "1", run = "plugin relative-motions 1", desc = "Move in relative steps" },
  { on = "2", run = "plugin relative-motions 2", desc = "Move in relative steps" },
  { on = "3", run = "plugin relative-motions 3", desc = "Move in relative steps" },
  { on = "4", run = "plugin relative-motions 4", desc = "Move in relative steps" },
  { on = "5", run = "plugin relative-motions 5", desc = "Move in relative steps" },
  { on = "6", run = "plugin relative-motions 6", desc = "Move in relative steps" },
  { on = "7", run = "plugin relative-motions 7", desc = "Move in relative steps" },
  { on = "8", run = "plugin relative-motions 8", desc = "Move in relative steps" },
  { on = "9", run = "plugin relative-motions 9", desc = "Move in relative steps" },
  { on = ["\\", "1"], run = "tab_switch 0", desc = "Switch to tab 1" },
  { on = ["\\", "2"], run = "tab_switch 1", desc = "Switch to tab 2" },
  { on = ["\\", "3"], run = "tab_switch 2", desc = "Switch to tab 3" },
  { on = ["\\", "4"], run = "tab_switch 3", desc = "Switch to tab 4" },
  { on = ["\\", "5"], run = "tab_switch 4", desc = "Switch to tab 5" },
  { on = ["\\", "6"], run = "tab_switch 5", desc = "Switch to tab 6" },
  { on = ["\\", "7"], run = "tab_switch 6", desc = "Switch to tab 7" },
  { on = ["\\", "8"], run = "tab_switch 7", desc = "Switch to tab 8" },
  { on = ["\\", "9"], run = "tab_switch 8", desc = "Switch to tab 9" },
  { on = ["t", "a"], run = "plugin mactag add", desc = "Tag selected files" },
  { on = ["t", "d"], run = "plugin mactag remove", desc = "Untag selected files" },
  { on = ["t", "l"], run = "shell --block -- fzf-tag | while read f; do ya emit reveal \"$f\"; ya emit toggle --state=on; done", desc = "List tagged files" },
  { on = "'", run = "plugin bookmarks jump", desc = "Open bookmark" },
  { on = [ "m", "a" ], run = "plugin bookmarks save", desc = "Save bookmark" },
  { on = [ "m", "d" ], run = "plugin bookmarks jump", desc = "Delete bookmark" },
  { on = [ "m", "c" ], run = "plugin bookmarks modify", desc = "Modify bookmark" },
]

[tasks]
prepend_keymap = [
  { on = "?", run = "help", desc = "Open help" },
  { on = "i", run = "inspect", desc = "Inspect the task" },
]

[spot]
prepend_keymap = [
  { on = "?", run = "help", desc = "Open help" },
  { on = "i", run = "close", desc = "Close the spot" },
  { on = "J", run = "swipe 1", desc = "Swipe to next file" },
  { on = "K", run = "swipe -1", desc = "Swipe to previous file" },
  { on = "y", run = "copy cell", desc = "Yank selected cell" },
]

[pick]
prepend_keymap = [
  { on = "?", run = "help", desc = "Open help" },
]

[input]
prepend_keymap = [
  { on = "<esc>", run = "close", desc = "cancel input" },
  { on = "?", run = "help", desc = "Open help" },
]

[confirm]
prepend_keymap = [
  { on = "?", run = "help", desc = "Open help" },
]

[cmp]
prepend_keymap = [
  { on = "?", run = "help", desc = "Open help" },
]

[filter]
prepend_keymap = [
  { on = "?", run = "help", desc = "Open help" },
]

[help]
prepend_keymap = [
  { on = "/", run = "filter", desc = "Search for help items" },
]
