# https://github.com/sxyazi/yazi/blob/shipped/yazi-config/preset/keymap-default.toml

[manager]
prepend_keymap = [
  { on = "<Tab>", run = [ "toggle", "arrow 1" ], desc = "Toggle selection" },
  { on = "<BackTab>", run = [ "toggle --state=off", "arrow -1" ], desc = "Toggle selection" },
  { on = "<A-j>", run = [ "toggle", "arrow 1" ], desc = "Toggle selection" },
  { on = "<A-k>", run = [ "toggle --state=off", "arrow -1" ], desc = "Toggle selection" },
  { on = "<A-a>", run = "toggle_all", desc = "Toggle select all" },
  { on = "<A-h>", run = 'shell -- ya emit toggle --state=off "${@: -1}"', desc = "Toggle select all" },
  { on = "i", run = "spot", desc = "Inspect file" },
  { on = "e", run = 'shell --block -- nvim "$@"', desc = "Edit file" },
  { on = "<Enter>", run = "plugin my-cmd 'smart enter'", desc = "Open shell / edit file" },
  { on = "<S-Enter>", run = "open --interactive", desc = "Open interactively" },
  { on = "?", run = "help", desc = "Open help" },
  { on = "!", run = "shell --interactive", desc = "Run a shell command" },
  { on = "~", run = "cd ~", desc = "Go to home directory" },
  { on = "q", run = "close", desc = "Close current tab, or quit if it is last tab" },
  { on = "Q", run = "quit", desc = "Exit" },
  { on = "<C-d>", run = "seek 5", desc = "Seek down 5 units in preview" },
  { on = "<C-u>", run = "seek -5", desc = "Seek up 5 units in preview" },
  { on = [ "g", "c" ], run = "noop" },
  { on = [ "g", "o" ], run = 'shell -- ya emit reveal "$(realpath "$0")"', desc = "Go to original" },
  { on = [ "g", "<Space>" ], run = "cd --interactive", desc = "Go interactively" },
  { on = [ "g", "r" ], run = 'shell -- ya emit cd "$(git rev-parse --show-toplevel)"', desc = "Go to git repo root" },
  { on = [ "g", "d" ], run = 'shell --block -- git diff "$0" | delta --$(background) --navigate --tabs=2 --line-numbers --side-by-side --paging=always --width=$(stty size < /dev/tty | choose 1)  | less -R', desc = "Git diff" },
  { on = [ "y", "c" ], run = "yank", desc = "Copy files" },
  { on = [ "y", "x" ], run = "yank --cut", desc = "Cut files" },
  { on = [ "y", "p" ], run = "copy path", desc = "Yank file path" },
  { on = [ "y", "f" ], run = "copy filename", desc = "Yank filename" },
  { on = "<Esc>", run = "plugin my-cmd 'smart esc'", desc = "Unyank, exit visual mode, clear selected, or cancel search" },
  { on = "j", run = "plugin my-cmd 'smart down'", desc = "Move cursor down" },
  { on = "k", run = "plugin my-cmd 'smart up'", desc = "Move cursor up" },
  { on = "<Down>", run = "plugin my-cmd 'smart down'", desc = "Move cursor down" },
  { on = "<Up>", run = "plugin my-cmd 'smart up'", desc = "Move cursor up" },
  { on = "<", run = "back", desc = "Back" },
  { on = ">", run = "forward", desc = "Forward" },
  { on = "J", run = "plugin my-cmd 'smart parent-down'", desc = "Go down in parent dir" },
  { on = "K", run = "plugin my-cmd 'smart parent-up'", desc = "Go up in parent dir" },
  { on = "N", run = "plugin my-cmd 'smart N'", desc = "Go to previous found / Create a file" },
  { on = "<C-v>", run = "plugin my-cmd 'smart vsplit'", desc = "Open file in vsplit" },
  { on = "<C-s>", run = "plugin my-cmd 'smart split'", desc = "Open file in split" },
  { on = "<C-g>", run = 'shell --block lazygit', desc = "LazyGit" },
  { on = "<C-f>", run = 'arrow 50%', desc = "Move cursor down half page" },
  { on = "<C-b>", run = 'arrow -50%', desc = "Move cursor up half page" },
  { on = "}", run = "plugin my-cmd 'smart create-tab'", desc = "Create new tab" },
  { on = "]", run = "plugin my-cmd 'smart next-tab'", desc = "Switch to next tab" },
  { on = [ "<Space>", "t" ], run = "tasks_show", desc = "Show task manager" },
  { on = [ "\\", "g" ], run = "plugin zoxide", desc = "Go to a directory" },
  { on = [ "\\", "f" ], run = "plugin fzf", desc = "Search files" },
  { on = [ "M", "." ], run = "linemode size_and_mtime", desc = "Linemode: size & mtime" },
  { on = [ "M", "s" ], run = "linemode size",           desc = "Linemode: size" },
  { on = [ "M", "p" ], run = "linemode permissions",    desc = "Linemode: permissions" },
  { on = [ "M", "b" ], run = "linemode btime",          desc = "Linemode: btime" },
  { on = [ "M", "m" ], run = "linemode mtime",          desc = "Linemode: mtime" },
  { on = [ "M", "o" ], run = "linemode owner",          desc = "Linemode: owner" },
  { on = [ "M", "n" ], run = "linemode none",           desc = "Linemode: none" },
  { on = [ "m", "s" ], run = "noop" },
  { on = [ "m", "p" ], run = "noop" },
  { on = [ "m", "b" ], run = "noop" },
  { on = [ "m", "m" ], run = "noop" },
  { on = [ "m", "o" ], run = "noop" },
  { on = [ "m", "n" ], run = "noop" },
  { on = [ "S", "m" ], run = [ "sort mtime --reverse=no", "linemode mtime" ], desc = "Sort by modified time" },
  { on = [ "S", "M" ], run = [ "sort mtime --reverse", "linemode mtime" ],    desc = "Sort by modified time (reverse)" },
  { on = [ "S", "c" ], run = [ "sort btime --reverse=no", "linemode btime" ], desc = "Sort by created time" },
  { on = [ "S", "C" ], run = [ "sort btime --reverse", "linemode btime" ],    desc = "Sort by created time (reverse)" },
  { on = [ "S", "e" ], run = "sort extension --reverse=no",                   desc = "Sort by extension" },
  { on = [ "S", "E" ], run = "sort extension --reverse",                      desc = "Sort by extension (reverse)" },
  { on = [ "S", "a" ], run = "sort alphabetical --reverse=no",                desc = "Sort alphabetically" },
  { on = [ "S", "A" ], run = "sort alphabetical --reverse",                   desc = "Sort alphabetically (reverse)" },
  { on = [ "S", "n" ], run = "sort natural --reverse=no",                     desc = "Sort naturally" },
  { on = [ "S", "N" ], run = "sort natural --reverse",                        desc = "Sort naturally (reverse)" },
  { on = [ "S", "s" ], run = [ "sort size --reverse=no", "linemode size" ],   desc = "Sort by size" },
  { on = [ "S", "S" ], run = [ "sort size --reverse", "linemode size" ],      desc = "Sort by size (reverse)" },
  { on = [ "S", "r" ], run = "sort random --reverse=no",                      desc = "Sort randomly" },
  { on = ["<A-Enter>", "c"], run = "plugin my-cmd 'on_selection copy'", desc = "Copy here" },
  { on = ["<A-Enter>", "C"], run = "plugin my-cmd 'on_selection copy-force'", desc = "Force-copy here" },
  { on = ["<A-Enter>", "m"], run = "plugin my-cmd 'on_selection move'", desc = "Move here" },
  { on = ["<A-Enter>", "M"], run = "plugin my-cmd 'on_selection move-force'", desc = "Force-move here" },
  { on = ["<A-Enter>", "n"], run = "plugin my-cmd 'on_selection move-new-dir'", desc = "Create folder with" },
  { on = ["<A-Enter>", "N"], run = "plugin my-cmd 'on_selection copy-new-dir'", desc = "Create folder with (copy)" },
  { on = ["<A-Enter>", "l"], run = "plugin my-cmd 'on_selection symlink'", desc = "Symlink here" },
  { on = ["<A-Enter>", "L"], run = "plugin my-cmd 'on_selection symlink-force'", desc = "Force-symlink here" },
  { on = ["<A-Enter>", "h"], run = "plugin my-cmd 'on_selection hardlink'", desc = "Hardlink here" },
  { on = ["<A-Enter>", "H"], run = "plugin my-cmd 'on_selection hardlink-force'", desc = "Force-hardlink here" },
  { on = ["<A-Enter>", "d"], run = "plugin my-cmd 'on_selection delete'", desc = "Delete" },
  { on = ["<A-Enter>", "e"], run = "plugin my-cmd 'on_selection edit'", desc = "Edit" },
  { on = ["<A-Enter>", "r"], run = "plugin my-cmd 'on_selection rename'", desc = "Rename" },
  { on = ["<A-Enter>", ":"], run = "plugin my-cmd 'on_selection exec'", desc = "Execute" },
  { on = ["<A-Enter>", "<C-d>"], run = 'shell --block -- [ $# -eq 2 ] && delta --$(~/.local/bin/background) --navigate --tabs=2 --line-numbers --side-by-side --paging=always --width=$(stty size < /dev/tty | choose 1) "$@" | less -R || true', desc = "Diff" },
  { on = ["z", "p"], run = "plugin toggle-pane max-preview", desc = "Zoom preview" },
  { on = ["z", "o"], run = "plugin toggle-pane ratio-1,4,0", desc = "Hide preview" },
  { on = ["z", "z"], run = "plugin toggle-pane max-current", desc = "Zoom current" },
]

[tasks]
prepend_keymap = [
  { on = "?", run = "help", desc = "Open help" },
  { on = "i", run = "inspect", desc = "Inspect the task" },
]

[spot]
prepend_keymap = [
  { on = "?", run = "help", desc = "Open help" },
  { on = "i", run = "close", desc = "Close the spot" },
  { on = "J", run = "swipe 1", desc = "Swipe to next file" },
  { on = "K", run = "swipe -1", desc = "Swipe to previous file" },
  { on = "y", run = "copy cell", desc = "Yank selected cell" },
]

[pick]
prepend_keymap = [
  { on = "?", run = "help", desc = "Open help" },
]

[input]
prepend_keymap = [
  { on = "<esc>", run = "close", desc = "Cancel input" },
  { on = "?", run = "help", desc = "Open help" },
]

[confirm]
prepend_keymap = [
  { on = "?", run = "help", desc = "Open help" },
]

[cmp]
prepend_keymap = [
  { on = "?", run = "help", desc = "Open help" },
]

[filter]
prepend_keymap = [
  { on = "?", run = "help", desc = "Open help" },
]

[help]
prepend_keymap = [
  { on = "/", run = "filter", desc = "Search for help items" },
]
