# https://github.com/sxyazi/yazi/blob/shipped/yazi-config/preset/keymap.toml

[manager]
prepend_keymap = [
  # { on = [ "g", "a" ], run = 'my-fev-command1', desc = "Just for test!" },
  { on = "<A-j>", run = [ 'select', 'arrow 1' ], desc = "Toggle selection" },
  { on = "<A-k>", run = [ 'select --state=false' ], desc = "Toggle selection" },
  { on = "<Enter>", run = 'plugin smart --args=enter --sync', desc = "Open shell / edit file" },
  { on = "<A-Enter>", run = [ 'open --interactive' ], desc = "Open selected files interactively" },
  { on = "?", run = 'help', desc = "Open help" },
  { on = "!", run = 'shell --interactive', desc = "Run a shell command" },
  { on = "~", run = 'cd ~', desc = "Go to the home directory" },
  { on = "q", run = 'close', desc = "Close the current tab, or quit if it is last tab" },
  { on = "Q", run = 'quit', desc = "Exit the process" },
  { on = "<C-d>", run = "seek 5", desc = "Seek down 5 units in the preview" },
  { on = "<C-u>", run = "seek -5", desc = "Seek up 5 units in the preview" },
  { on = [ "y", "f" ], run = "yank", desc = "Yank selected files (copy)" },
  { on = [ "y", "p" ], run = "copy path", desc = "Copy the file path" },
  { on = [ "y", "n" ], run = "copy filename", desc = "Copy the filename" },
  { on = "<Esc>", run = 'plugin smart --args=esc --sync', desc = "Unyank, exit visual mode, clear seleted, or canel search" },
  { on = [ "\\", "g" ], run = "plugin my-fzf --args=z", desc = "Jump to a directory using zoxide" },
  { on = [ "\\", "f" ], run = "plugin my-fzf --args=fd", desc = "Jump to a directory or reveal a file using fzf" },
  { on = [ "\\", "s" ], run = "plugin my-fzf --args=fif", desc = "Search files by content using repgrep" },
  { on = [ "\\", "r" ], run = "plugin my-fzf --args=mru", desc = "Search files by content using repgrep" },
  { on = [ "\\", "R" ], run = "plugin my-fzf --args=git", desc = "Search files by content using repgrep" },
  { on = [ "s", "m" ], run = [ "sort modified --reverse=no", "linemode mtime" ], desc = "Sort by modified time" },
  { on = [ "s", "M" ], run = [ "sort modified --reverse", "linemode mtime" ],    desc = "Sort by modified time (reverse)" },
  { on = [ "s", "c" ], run = [ "sort created --reverse=no", "linemode ctime" ],  desc = "Sort by created time" },
  { on = [ "s", "C" ], run = [ "sort created --reverse", "linemode ctime" ],     desc = "Sort by created time (reverse)" },
  { on = [ "s", "e" ], run = "sort extension --reverse=no",                      desc = "Sort by extension" },
  { on = [ "s", "E" ], run = "sort extension --reverse",                         desc = "Sort by extension (reverse)" },
  { on = [ "s", "a" ], run = "sort alphabetical --reverse=no",                   desc = "Sort alphabetically" },
  { on = [ "s", "A" ], run = "sort alphabetical --reverse",                      desc = "Sort alphabetically (reverse)" },
  { on = [ "s", "n" ], run = "sort natural --reverse=no",                        desc = "Sort naturally" },
  { on = [ "s", "N" ], run = "sort natural --reverse",                           desc = "Sort naturally (reverse)" },
  { on = [ "s", "s" ], run = [ "sort size --reverse=no", "linemode size" ],      desc = "Sort by size" },
  { on = [ "s", "S" ], run = [ "sort size --reverse", "linemode size" ],         desc = "Sort by size (reverse)" },
  { on = [ "s", "r" ], run = "sort random --reverse=no",                         desc = "Sort randomly" },
  { on = "i", run = 'plugin searchjump --args=autocd', desc = "Searchjump" },
  { on = "I", run = 'plugin keyjump --args=global', desc = "Keyjump global" },
  { on = "[b", run = "back", desc = "Go back to the previous directory" },
  { on = "]b", run = "forward",  desc = "Go forward to the next directory" },
  { on = "[t", run = "tab_switch -1 --relative", desc = "Switch to the previous tab" },
  { on = "]t", run = "tab_switch 1 --relative",  desc = "Switch to the next tab" },
  { on = "F", run = "plugin smart-filter",  desc = "Smart filter" },
]

[tasks]
prepend_keymap = [
  { on = "?", run = 'help', desc = "Open help" },
]

[select]
prepend_keymap = [
  { on = "?", run = 'help', desc = "Open help" },
]

[input]
prepend_keymap = [
  { on = "<esc>", run = 'close', desc = "cancel input" },
  { on = "?", run = 'help', desc = "Open help" },
]

[confirm]
prepend_keymap = [
  { on = "?", run = 'help', desc = "Open help" },
]

[completion]
prepend_keymap = [
  { on = "?", run = 'help', desc = "Open help" },
]

