# A TOML linter such as https://taplo.tamasfe.dev/ can use this schema to validate your config.
# If you encounter any issues, please make an issue at https://github.com/yazi-rs/schemas.
# https://github.com/sxyazi/yazi/blob/shipped/yazi-config/preset/yazi-default.toml
"$schema" = "https://yazi-rs.github.io/schemas/yazi.json"

[manager]
ratio = [1, 2, 2]
sort_by = "mtime"
sort_reverse = true
sort_dir_first = true
sort_sensitive = false
linemode = "size_and_mtime"
show_hidden = true
show_symlink = true
scrolloff = 5

[preview]
wrap = "no"
tab_size = 2

[opener]
extract = [
	{ run = 'ouch d -y "$@"', desc = "Extract here", for = "macos" },
	{ run = 'ouch d -y "$@"', desc = "Extract here", for = "unix" },
	{ run = 'ya pub extract --list %*',   desc = "Extract here", for = "windows" },
]
play = [
	{ run = 'open "$@"', for = "macos" },
	{ run = 'mpv --force-window "$@"', orphan = true, for = "unix" },
	{ run = 'mpv --force-window %*', orphan = true, for = "windows" },
	{ run = '''mediainfo "$1"; echo "Press enter to exit"; read _''', block = true, desc = "Show media info", for = "unix" },
]

[tasks]
micro_workers = 10
macro_workers = 25
bizarre_retry = 5
image_alloc = 536870912  # 512MB
image_bound = [0, 0]
suppress_preload = false

[plugin]
prepend_previewers = [
	{ mime = "image/vnd.djvu", run = "noop" },
	# Archive
	{ mime = "application/zip", run = "ouch" },
	{ mime = "application/gzip", run = "ouch" },
	{ mime = "application/{tar,bzip*,7z-compressed,xz,rar}", run = "ouch" },
]

prepend_fetchers = [
	{ id = "git", name = "*", run = "git" },
	{ id = "git", name = "*/", run = "git" },
	{ id = "mactag", name = "*", run = "mactag" },
	{ id = "mactag", name = "*/", run = "mactag" },
]

[log]
enabled = false
