# A TOML linter such as https://taplo.tamasfe.dev/ can use this schema to validate your config.
# If you encounter any issues, please make an issue at https://github.com/yazi-rs/schemas.
# https://github.com/sxyazi/yazi/blob/shipped/yazi-config/preset/yazi-default.toml
"$schema" = "https://yazi-rs.github.io/schemas/yazi.json"

[mgr]
ratio = [1, 2, 2]
sort_by = "mtime"
sort_reverse = true
sort_dir_first = true
sort_sensitive = false
linemode = "size_and_mtime"
show_hidden = true
show_symlink = true
scrolloff = 5

[opener]
unzip = [
	{ run = 'unzip "$0"', desc = "Extract here", for = "unix" }
]
tar = [
	{ run = 'tar -xzf "$0"', desc = "Extract here", for = "unix" }
]

[open]
prepend_rules = [
	{ mime = "application/zip", use = ["unzip"] },
	{ name = "*.{tar,tar.*,tgz}", use = ["tar"] },
]

[preview]
wrap = "no"
tab_size = 2

[plugin]
prepend_fetchers = [
	{ id = "git", name = "*", run = "git" },
	{ id = "git", name = "*/", run = "git" },
]
