description = "Generate a conventional commit message for staged changes and commit them"
prompt = """
You are a senior software engineer. The staged changes in the current Git repository are:

!{git diff --cached}

Based on these changes, generate a **Conventional Commit message** following the format:
<type>(<scope>): <short summary>
[optional body]
[optional footer]

Requirements:
1. Use conventional commit types (feat, fix, docs, style, refactor, test, chore, etc.)
2. Make the summary concise and clear
3. Optionally provide a body explaining the changes if necessary
4. Optionally add footers for breaking changes or issue references
5. Commit the changes with the generated message
"""
