[colors.primary]
background = "#060015"
foreground = "#c4c8cf"
dim_foreground = "#7f849c"
bright_foreground = "#cdd6f4"

[colors.normal]
black   = "#131226"
red     = "#eb605e"
green   = "#7fce9a"
yellow  = "#f3b681"
blue    = "#77b0f8"
magenta = "#8a6df6"
cyan    = "#8beeef"
white   = "#a8b2c9"

[colors.bright]
black   = "#555572"
red     = "#ee8683"
green   = "#aefcac"
yellow  = "#fbe9b1"
blue    = "#a1dbfb"
magenta = "#c093dc"
cyan    = "#bcfce5"
white   = "#cfe2e6"

[colors.cursor]
text = "#ffffff"
cursor = "#528bff"

[colors.selection]
text = "#b6ccfa"
background = "#282099"

[colors.search.matches]
foreground = "#1e1e2e"
background = "#878ba2"

[colors.search.focused_match]
foreground = "#1e1e2e"
background = "#a1c281"

[colors.footer_bar]
foreground = "#b6ccfa"
background = "#2e315e"

[colors.hints.start]
foreground = "#1e1e2e"
background = "#f9e2af"

[colors.hints.end]
foreground = "#1e1e2e"
background = "#a6adc8"

