# Default colors
[colors.primary]
background = "#fefefe"
foreground = "#323156"
dim_foreground = "#8c8fa1"
bright_foreground = "#4c4f69"

# Normal colors
[colors.normal]
black   = "#000000"
red     = "#bd3628"
green   = "#677521"
yellow  = "#b69931"
blue    = "#426eac"
magenta = "#8053a4"
cyan    = "#4f99a2"
white   = "#fefefe"

# Bright colors
[colors.bright]
black   = "#4c4c4c"
red     = "#c55849"
green   = "#87992d"
yellow  = "#e7c341"
blue    = "#5d84b7"
magenta = "#9572b2"
cyan    = "#64a6ad"
white   = "#cecece"

[colors.cursor]
text = "#eff1f5"
cursor = "#526fff"

[colors.selection]
text = "#191919"
background = "#c6dcfb"

[colors.search.matches]
foreground = "#eff1f5"
background = "#6c6f85"

[colors.search.focused_match]
foreground = "#eff1f5"
background = "#ec6e30"

[colors.footer_bar]
foreground = "#4a4c53"
background = "#c2cdd3"

[colors.hints.start]
foreground = "#eff1f5"
background = "#df8e1d"

[colors.hints.end]
foreground = "#eff1f5"
background = "#6c6f85"
