[env]
TERM = "alacritty"
LANG = "en_US.UTF-8"

[font]
size = 12.0
normal = { family = "FiraCode Nerd Font", style = "Light" }
bold = { family = "FiraCode Nerd Font", style = "SemiBold" }
italic = { family = "JetBrainsMono Nerd Font", style = "Thin Italic" }
bold_italic = { family = "JetBrainsMono Nerd Font", style = "SemiBold Italic" }
offset = { x = 0, y = 1 }
glyph_offset = { x = 0, y = 0 }

[cursor]
style = { shape = "Block", blinking = "Always" }
blink_interval = 555

[colors]
draw_bold_text_with_bright_colors = true

[keyboard]
bindings = [
  { key = "Left", mods = "Super", chars = "\u0001" },
  { key = "Left" , mods = "Alt", chars = "\u001b\u0062" },
  { key = "Right", mods = "Super", chars = "\u0005" },
  { key = "Right", mods = "Alt", chars = "\u001b\u0066" },
  { key = "Back", mods = "Super", chars = "\u0015" },
  { key = "Delete", mods = "Super", chars = "\u001b\u006b" },
  { key = "Back", mods = "Alt", chars = "\u0017" },
  { key = "Delete", mods = "Alt", chars = "\u001b\u0064" },
  { key = "Z", mods = "Super", chars = "\u0018u" },
  { key = "T", mods = "Super", action = "None" },
  { key = "=", mods = "Super", action = "IncreaseFontSize" },
  { key = "-", mods = "Super", action = "DecreaseFontSize" },
  { key = "Tab", mods = "Control", chars = "\u0000\u006e" },
  { key = "Tab", mods = "Shift|Control", chars = "\u0000\u0010" },
  { key = "{", mods = "Super|Shift", action = "ToggleViMode" },
  { key = "Space", mods = "Super|Alt|Control|Shift", chars = "\u0000" },
  { key = "[", mods = "Super", chars = "\u0000\u005b" },
  { key = "]", mods = "Super", chars = "\u0000\u005d" },
  { key = "1", mods = "Control", chars = "\u0000\u0031" },
  { key = "2", mods = "Control", chars = "\u0000\u0032" },
  { key = "3", mods = "Control", chars = "\u0000\u0033" },
  { key = "4", mods = "Control", chars = "\u0000\u0034" },
  { key = "5", mods = "Control", chars = "\u0000\u0035" },
  { key = "6", mods = "Control", chars = "\u0000\u0036" },
  { key = "7", mods = "Control", chars = "\u0000\u0037" },
  { key = "8", mods = "Control", chars = "\u0000\u0038" },
  { key = "9", mods = "Control", chars = "\u0000\u0039" },
  { key = "Enter", mods = "Control", chars = "\u001b[13;5u" },
  { key = "Enter", mods = "Shift", chars = "\u001b[13;2u" },
  { key = "O", mods = "Super", chars = "\u0000\u000f" },
]

[mouse]
hide_when_typing = true

[selection]
save_to_clipboard = true
semantic_escape_chars = ",│`|:\"' ()[]{}<>"

[scrolling]
history = 10000
multiplier = 4

[window]
decorations = "Buttonless"
dimensions = { columns = 120, lines = 58 }
padding = { x = 2, y = 2 }
dynamic_padding = true
option_as_alt = "OnlyLeft"
opacity = 0.90
blur = true

[[hints.enabled]]
command = "open"
hyperlinks = true
post_processing = true
persist = false
mouse = { enabled = true, mods = "Shift" }
binding = { key = "J", mods = "Super" }
regex = "(ipfs:|ipns:|magnet:|mailto:|gemini://|gopher://|https://|http://|news:|file:|git://|ssh:|ftp://)[^\u0000-\u001F\u007F-\u009F<>\"\\s{-}\\^⟨⟩`]+"

[general]
import = ["~/.config/alacritty/colors.toml"]

[terminal]

shell = { program = "tmux" }
