#!/bin/zsh
PATH=/opt/homebrew/bin:$PATH
# rg_prefix='rg --column --line-number --no-heading --color=always --smart-case'
# fzf --bind "start:reload:$rg_prefix '' || true" \
#     --bind "change:reload:$rg_prefix {q} || true" \
#     --bind 'enter:become(nvim {1} +{2})' \
#     --ansi --disabled \
#     --delimiter ':' \
#     --preview 'sed -n {2}p {1} 2>/dev/null | rg --color=always --smart-case {q}' \
#     --preview-window wrap

# 1. Search for text in files using Ripgrep
# 2. Interactively narrow down the list using fzf
# 3. Open the file in Vim
# rg --ignore-vcs --glob '!**/.git/**' --color=always --line-number --no-heading --smart-case "${*:-}" |
#   fzf --ansi \
#       --color "hl:-1:underline,hl+:-1:underline:reverse" \
#       --delimiter : \
#       --preview 'bat --color=always {1} --highlight-line {2}' \
#       --preview-window 'up,60%,border-bottom,+{2}+3/3,~3' \
#       --bind 'enter:become(nvim {1} +{2})'

RG_PREFIX="rg --ignore-vcs --glob '!**/.git/**' --column --line-number --no-heading --color=always --smart-case "
[ "$1" = -o ] && { enter=accept; shift; } || enter="become(nvim {1} +{2})"
INITIAL_QUERY="${*:-}"
fzf --ansi --disabled --query "$INITIAL_QUERY" -m \
    --color "hl:-1:underline,hl+:-1:underline:reverse" \
    --bind "start:reload:$RG_PREFIX {q}" \
    --bind "change:reload:sleep 0.1; $RG_PREFIX {q} || true" \
    --bind "alt-enter:unbind(change,alt-enter)+change-prompt(2. fzf> )+enable-search+clear-query" \
    --delimiter : \
    --preview 'bat --color=always {1} --highlight-line {2}' \
    --preview-window 'up,60%,border-bottom,+{2}+3/3,~3' \
    --bind "enter:$enter"
