#probably=============================================================================
# basic.toml --- basic configuration example for SpaceVim
# Copyright (c) 2016-2022 Wang Shidong & Contributors
# Author: Wang Shidong < wsdjeg@outlook.com >
# URL: https://spacevim.org
# License: GPLv3
#=============================================================================

# All SpaceVim option below [option] section
[options]
  # set spacevim theme. by default colorscheme layer is not loaded,
  # if you want to use more colorscheme, please load the colorscheme
  # layer
  colorscheme = "one"
  # colorscheme_bg = "dark"
  # Disable guicolors in basic mode, many terminal do not support 24bit
  # true colors
  # enable_guicolors = true
  # Disable statusline separator, if you want to use other value, please
  # install nerd fonts
  statusline_separator = "arrow"
  # statusline_iseparator = "nil"
  buffer_index_type = 4
  windows_index_type = 3
  guifont= "FiraCode Nerd Font:h12"
  enable_statusline_tag = true
  enable_statusline_bfpath = true
  enable_powerline_fonts = true
  enable_tabline_ft_icon = true
  enable_statusline_mode = false
  enable_statusline_ft_icon = true
  statusline_unicode_symbols = true
  statusline_left = [
    "winnr",
    # "filename",
    "major mode",
    "syntax_checking",
    "version control info",
    "search count",
  ]
  statusline_right = [
    "cursorpos",
    "percentage",
  ]
  # Enable vim compatible mode, avoid changing origin vim key bindings
  vimcompatible = false
  # automatic_update = true
  bootstrap_before = "vimrc#before"
  bootstrap_after = "vimrc#after"
  default_indent = 2
  expand_tab = true
  wrap_line = true
  windows_leader = ""
  filemanager = "nerdtree"
  filetree_direction = "left"
  timeoutlen = 600
  github_username = "twio142"
  enable_os_fileformat_icon = true
  escape_key_binding = "jh"
  file_searching_tools = ['fd', 'fd --type f -H -L --exclude ".DS_Store" --exclude ".git"']

  todo_labels = ["DIGIN", "TEST", "TODO", "BUG", "HERE", "EDITED", "FINDOUT", "fixme", "digin", "here", "edited", "test", "debug", "findout"]
  todo_prefix = "@"

  project_rooter_patterns = ['.git/', '_darcs/', '.hg/', '.bzr/', '.svn/', 'info.plist', 'Package.swift', 'go.mod', '.obsidian/']
  project_rooter_outermost = false

[[layers]]
  name = "autocomplete"
  auto_completion_return_key_behavior = "smart"
  auto_completion_tab_key_behavior = "smart"
  auto_completion_delay = 500

[[layers]]
  name = "checker"

[[layers]]
  name = "colorscheme"

[[layers]]
  name = "core"
  enable_filetree_gitstatus = true
  enable_filetree_filetypeicon = true
  enable_netrw = true

[[layers]]
  name = "core#banner"

[[layers]]
  name = "core#statusline"

[[layers]]
  name = "core#tabline"

# [[layers]]
  # name = "ctrlp"

[[layers]]
  name = "ctrlspace"
  enable-spacevim-styled-keys = true

[[layers]]
  name = "edit"

[[layers]]
  name = "format"

[[layers]]
  name = "fzf"

[[layers]]
  name = "git"
  git_diff_position = '20split'

[[layers]]
  name = "github"

[[layers]]
  name = "gtags"
  gtagslabel = "ctags"
  auto_update = false

[[layers]]
  name = "incsearch"

[[layers]]
  name = "lang#go"

[[layers]]
  name = "lang#javascript"

[[layers]]
  name = "lang#markdown"
  enabled_foramtters = ["prettier"]

[[layers]]
  name = "lang#python"
  python_interpreter = "~/.local/bin/py3"

[[layers]]
  name = "lang#swift"

[[layers]]
  name = "leaderf"

[[layers]]
  name = "lsp"
  enabled_clients = ["tsserver", "gopls", "pylsp", "sourcekit", "marksman"]

[[layers]]
  name = "shell"
  default_position = "bottom"
  default_height = 35

[[layers]]
  name = "sudo"

[[layers]]
  name = "telescope"

[[layers]]
  name = "tmux"

[[layers]]
  name = "tools"

# [[layers]]
  # name = "treesitter"

[[layers]]
  name = "ui"
  enable_cursorword = true
  indentline_char = '┊'
  cursorword_exclude_filetype = ['startify']

[[layers]]
  name = "VersionControl"

[[custom_plugins]]
  repo = "easymotion/vim-easymotion"

[[custom_plugins]]
  repo = "github/copilot.vim"
  merged = false

# [[custom_plugins]]
  # repo = "justinmk/vim-sneak"
  
[[custom_plugins]]
  repo = "kshenoy/vim-signature"

[[custom_plugins]]
  repo = "ryanoasis/vim-devicons"

[[custom_plugins]]
  repo = "tiagofumo/vim-nerdtree-syntax-highlight"

[[custom_plugins]]
  repo = "tpope/vim-obsession"

[[custom_plugins]]
  repo = "ybian/smartim"
  merged = false

[[custom_plugins]]
  repo = "zzhirong/vim-easymotion-zh"
